### ISSUE TITLE
RuntimeError: Bad magic number in .pyc file

### ISSUE THREAD

**Issue by ghost** [bethesirius/ChosunTruck#20] opened 2017-02-19 15:47 UTC
Hi i am using Windows 10 64bit but when i run the .pyc file it comes up with this error all the time but i had to record it and slow it down to 0.05x speed so i could see it but that only just managed to show it so i screenshotted it. It is below. Thanks!

**Comment by ghost** [comment] 2017-02-19 17:57
Ok this is what i have got so far.
![screenshot 157](https://cloud.githubusercontent.com/assets/25883025/23104820/e22cf3ba-f6cc-11e6-8506-53926272baaf.png)

**Comment by zappybiby** [comment] 2017-02-19 18:05
Usually this is caused by wrong python version

Go into the pyc file and see what the magic number is

Then compare it to this list http://stackoverflow.com/a/514395/7430976
To see if you have the correct version.

**Comment by ghost** [comment] 2017-02-19 18:47
Where can i find it?

**Comment by ghost** [comment] 2017-02-19 18:49
Also what python is it you used?

**Comment by ghost** [comment] 2017-02-19 19:15
Because i use python 3.6.0

**Comment by zappybiby** [comment] 2017-02-19 19:40
Ok, so I used HexEdit to read the `__init__.pyc ` file located in
`...\ChosunTruck\ChosunTruck\linux\tensorbox\utils` among other locations.

The first two byes were "03 F3" which when reversed to "F3 03" give the decimal value 62211

According to the table, this means that it was built with **Python 2.5b3**

@chi3236  do we need to add "Python 2.5b3" (Python 2.7) to the prerequisites?

**Comment by ghost** [comment] 2017-02-19 20:33
Hmm it is PyScaffold that one so i don't know :/

**Comment by ghost** [comment] 2017-02-19 20:36
If you want we can do teamviewer and you could help me?
Another thing is, it is caused by me using windows not linux?

**Comment by zappybiby** [comment] 2017-02-19 20:40
https://www.python.org/downloads/release/python-2712/

Python 2.7 is backwards compatible with 2.5. See if that works...

**Comment by zappybiby** [comment] 2017-02-19 20:41
So the windows version doesn't use tensorbox, so there is no python code to execute. It is c++, you will need Visual Studio 2013

**Comment by ghost** [comment] 2017-02-19 20:42
oh i have Visual Studio 2015

**Comment by zappybiby** [comment] 2017-02-19 20:44
That works, but you will need to build the OpenCV CUDA libraries with CMake. The current versions of OpenCV use 'shared libraries', meaning they took a whole bunch of libraries and put them into one. For our code, we need each library separate, also called 'static libraries'.

Since that is pretty difficult, it is much easier to use Visual Studio 2013 and follow the troubleshooting instructions in our README to get those libraries. You can have both 2013 and 2015 on your system, it will let you choose which one you want to use when starting the program.

**Comment by ghost** [comment] 2017-02-19 20:52
I cannot get Visual Studio 2013 because i have to be this subscriber

**Comment by zappybiby** [comment] 2017-02-19 20:53
You need to login with your Microsoft account. Visual Studio 2013 is free to use once you login.

**Comment by ghost** [comment] 2017-02-19 20:55
ahh ok

**Comment by ghost** [comment] 2017-02-19 20:57
Still won't let me get it and will only let me get 2015 :/

**Comment by zappybiby** [comment] 2017-02-19 21:09
Ok, lets do teamviewer I guess.

My email is blittle65@gmail.com. Send me the ID and PW

**Comment by ghost** [comment] 2017-02-19 21:19
ok i sent it, sorry i was AFK.

**Comment by zappybiby** [comment] 2017-02-22 17:35
How did it go? Are you still having this issue or can we close it?

**Comment by ghost** [comment] 2017-02-22 22:03
i haven't tried yet as i got a reply on one of the vids from my comment saying Windows version does not work so :/

**Comment by ghost** [comment] 2017-02-22 22:03
but i could try
and the only problem is i don't know how and what to do as the Windows Instructions are a little bit small and there is no tutorial :( Sorry if i cause any bother.

**Comment by zappybiby** [comment] 2017-02-22 22:17
Windows version works but we are still in the process of implementing input (see pull requests). As of right now input is not implemented and so the Windows version only detects lines for now. Input is essentially finished, just needs to be pushed + fine tuned.

I'll try to see if I can update the tutorial. What prerequisites do you already have? Did you install the Cuda Toolkit? Do you now have Visual Studio 2013? Did you get the Nuget packages?

You should open a new issue if the answer to any of those is no.

**Comment by ghost** [comment] 2017-02-23 10:02
i have got Visual Studio 2013 but there is no build option now, well there was never one but i haven't got the CUDA Toolkit

**Comment by zappybiby** [comment] 2017-02-23 15:43
Follow the instructions in our readme to install the CUDA Toolkit...

**Comment by ghost** [comment] 2017-02-23 16:20
ok

**Comment by ghost** [comment] 2017-02-23 16:47
I'm having problems, i have installed the CUDA Toolkit and Visual Studio but now when i try to get the NuGet Gallery Opencv CUDA Contrib vc12 Release Build 3.1.0. It is coming up with errors in VS2013

PM> Install-Package opencvcuda-release
Install-Package : The current environment doesn't have a solution open.
At line:1 char:1
+ Install-Package opencvcuda-release
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetNoActiveSolution,NuGet.PowerShell.Commands.InstallPackageCommand
 
PM>

**Comment by zappybiby** [comment] 2017-02-23 16:51
... you need to create the solution

Save all (Crtl +shift + s) then it will ask you where you want to save the .sln file. Then open that .sln file and repeat nuget

**Comment by ghost** [comment] 2017-02-23 16:51
umm ok

**Comment by ghost** [comment] 2017-02-23 16:52
it isn't doing anything. i sent teamviewer stuff through email again.

**Comment by ghost** [comment] 2017-02-23 17:25
Thanks to zappybiby, just about everything is working but for some reason i am getting errors while building the solution and i have screenshotted my screen twice to show list of errors.
http://imgur.com/a/pLht9

**Comment by zappybiby** [comment] 2017-02-23 17:27
Those are linker errors. Look at our Readme on how to fix that.

**Comment by ghost** [comment] 2017-02-23 17:28
ok

**Comment by ghost** [comment] 2017-02-23 17:34
Right it fixed most but now i have this error
![image](https://cloud.githubusercontent.com/assets/25883025/23271147/63410fe4-f9ee-11e6-8f59-9ce0099a2732.png)

**Comment by zappybiby** [comment] 2017-02-23 17:36
Nuget should have made a folder for you with all of the required libraries. This is usually in your main directory (\ChosunTruck)

You need to link to those, not to the opencv folder.

**Comment by ghost** [comment] 2017-02-23 17:39
ahh ok

**Comment by ghost** [comment] 2017-02-23 17:39
which one redist or the other?

**Comment by ghost** [comment] 2017-02-23 17:43
i tried both and still the same error

**Comment by ghost** [comment] 2017-02-23 17:45
![image](https://cloud.githubusercontent.com/assets/25883025/23271568/d2dd669e-f9ef-11e6-9d39-e6c5b40697aa.png)

**Comment by ghost** [comment] 2017-02-23 17:56
Now it says this.
![image](https://cloud.githubusercontent.com/assets/25883025/23271956/691f4130-f9f1-11e6-9d7b-9490b2b46bc8.png)

**Comment by AntonioCS** [comment] 2017-02-23 18:05
@keyring52 Please google the error msg

Second thing I found with a quick google search: http://stackoverflow.com/questions/15978035/cannot-open-input-file-opencv-calib3d243d-lib

**Comment by ghost** [comment] 2017-02-23 18:18
ahh i'll try that
EDIT: i checked and everthing is alright and all correct it just keeps saying that error so i'll reinstall the opencv thing

**Comment by ghost** [comment] 2017-02-23 18:21
wait if i take the "opencv_calib3d310.lib;" out it goes to next one and says same thing cannot open.

**Comment by zappybiby** [comment] 2017-02-23 18:25
Ok, so all of those files are required for the program to run. If you take one out, it moves on to the next one, but it will not run without that file. You need to search for that file on your computer. Use the search box in your chosuntruck directory to find the folder containing the files you need.

**Comment by ghost** [comment] 2017-02-23 18:26
i have found them but nothing is wrong to me it all looks how it should

**Comment by zappybiby** [comment] 2017-02-23 18:26
Again, opencv 3.0+ switched to shared libraries. We need static libraries that are obtained from nuget. You need to link to the nuget libraries. Reinstalling opencv will not fix this.

**Comment by zappybiby** [comment] 2017-02-23 18:27
All I can tell you is that he error you are gettng is because Visual studio is not finding the file. Try altering the include directories again. Double check your linker directories too

**Comment by ghost** [comment] 2017-02-23 18:28
ok
i kinda changed the directories and it all shows up properly and works then i get this.
![image](https://cloud.githubusercontent.com/assets/25883025/23273172/e52b87e4-f9f5-11e6-9a24-d9fc9b6874a8.png)

**Comment by ghost** [comment] 2017-02-23 18:35
Reinstalled it and i get this now
![image](https://cloud.githubusercontent.com/assets/25883025/23273419/d4f6004c-f9f6-11e6-8f38-e4e3def07f66.png)

**Comment by zappybiby** [comment] 2017-02-23 19:19
You are getting the same error (lnk1104)

Look at solutions here: http://stackoverflow.com/questions/133698/why-does-fatal-error-lnk1104-cannot-open-file-c-program-obj-occur-when-i-c

Maybe run VS as admin.

**Comment by ghost** [comment] 2017-02-23 20:57
It's gonna have to be teamviewer again as it isn't working again and it is different error now

**Comment by ghost** [comment] 2017-02-23 21:11
wait nevermind i'll try again later

**Comment by zappybiby** [comment] 2017-02-24 02:49
@keyring52, you need to close this issue and, if you are still having problems, create a new one called "Error LNK1104". This thread has gone completely off topic from its first post. Paging @chi3236 @bethesirius, can one of you close this! Thanks

**Comment by ghost** [comment] 2017-02-24 09:10
Closed issue :)

**Closed as completed** 2017-02-24 09:10 UTC
Labels: Windows
